#!/bin/bash -x
CACHE_SRC=${1:-"cache_volumes"}
export CRDS_TEST_ROOT=${HOME}/${CACHE_SRC}
export CRDS_PATH=${CRDS_TEST_ROOT}/crds-cache-default-test
tmpcache=${HOME}/tmp_cache

# if image was built with test cache (default) and mounted cache folder is empty
# move the contents of tmp_cache into the mounted directory ("cache_volumes")
if [[ ! -d "${CRDS_PATH}" && -d "${tmpcache}" ]]; then
    mv ${tmpcache}/* ${CRDS_TEST_ROOT}/.
fi
