#!/bin/bash -xu

export CRDS_TEST_ROOT=/home/developer/tmp_cache
export CRDS_PATH=$CRDS_TEST_ROOT/crds-cache-default-test
export CRDS_TESTING_CACHE=$CRDS_TEST_ROOT/crds-cache-test

contexts=(hst.pmap 
hst_0001.pmap
hst_0294.pmap
hst_0315.pmap
hst_0379.pmap
hst_0500.pmap
hst_0508.pmap
hst_0628.pmap 
hst_0633.pmap
hst_0691.pmap
hst_0772.pmap
hst_0779.pmap
hst_0857.pmap
hst_0978.pmap
hst_0980.pmap
hst_1099.pmap
hst_acs_biasfile_0005.rmap
hst_acs_biasfile_0250.rmap)

refs=(l2d0959cj_pfl.fits 
	n7p1032ao_apt.fits 
	q5417413o_pct.fits 
	xaf1429el_wcp.fits 
	y2r1559to_apt.fits 
	y2r16006o_pct.fits 
	y951738kl_hv.fits 
	yas2005el_hv.fits 
	p7d1548qj_idc.fits 
	3241637sm_tmt.fits 
	41g16069m_tmg.fits 
	43h1909cm_tmc.fits 
	43h1240om_tmc.fits)

export CRDS_SERVER_URL=https://hst-crds.stsci.edu
export CRDS_CONTEXT=hst-operational

for ctx in ${contexts[@]}
do
    echo "Syncing mappings under ${ctx}"
    python -m crds.sync --contexts $ctx --stats --log-time --check-sha1sum --repair-files --organize=flat
done

echo "Syncing current operational context"
python -m crds.sync --contexts hst-operational --stats --log-time --check-sha1sum --repair-files --organize=flat

echo "Syncing select reference files"
python -m crds.sync --files ${refs[@]} --stats --log-time

echo "Syncing select instrument mapping and references" 
python -m crds.sync --contexts hst_cos.imap --fetch-references --log-time --stats



