#!/bin/bash
#!/bin/bash
###########################################
# USER SETTINGS - configure these as needed
###########################################
if [[ ! -f .env ]]; then
    echo ".env file not found - using template"
    cp .env.template .env
fi

source .env
export IMAGE_TAG=$IMAGE_TAG
export MAST_API_TOKEN=$MAST_API_TOKEN
export CRDS_CONTEXT=$CRDS_CONTEXT
export CRDS_SERVER_URL=$CRDS_SERVER_URL
export GH_USER=$GH_USER
export CRDS_BRANCH=$CRDS_BRANCH
export CRDS_SERVER_URL=$CRDS_SERVER_URL
source scripts/pathfinder $CRDS_ROOT

export IMAGE_REPO=alphasentaurii/crds-docker-testing
export DOCKER_IMAGE=${IMAGE_REPO}:${IMAGE_TAG}
export CRDS_REPO=https://github.com/${GH_USER}/crds
export BASE=debian
export BASE_TAG=bookworm-slim
export BASE_IMAGE=${BASE}:${BASE_TAG}
export DEV_HOME="."
export THOME=/home/developer

if [[ "${IMAGE_TAG}" == "latest" || "${IMAGE_TAG}" == "slim" ]]; then
    source templates/${IMAGE_TAG}
else
    export CACHE_SRC=$CACHE_SRC #"cache_volumes"
    export DOWNLOAD=$DOWNLOAD
    export SYNC=$SYNC
    export RUN_PARS=$RUN_PARS
fi

export CRDS_TEST_ROOT=${THOME}/${CACHE_SRC}
export CRDS_PATH=${CRDS_TEST_ROOT}/crds-cache-default-test
export CRDS_TESTING_CACHE=${CRDS_TEST_ROOT}/crds-cache-test
