#!/bin/bash
export CRDS_SERVER_URL=https://jwst-crds.stsci.edu
export CRDS_CONTEXT=latest
python -m crds.sync --all --stats --log-time --check-sha1sum --repair-files --organize=flat
python -m crds.sync --files jwst_niriss_flat_0000.fits jwst_miri_flat_0006.fits --stats --log-time