#!/bin/bash -xu

export CRDS_TEST_ROOT=/home/developer/tmp_cache
export CRDS_PATH=$CRDS_TEST_ROOT/crds-cache-default-test
export CRDS_TESTING_CACHE=$CRDS_TEST_ROOT/crds-cache-test

jwstcontexts=(jwst_1091.pmap 
jwst_1090.pmap
jwst_0301.pmap
jwst_0341.pmap
jwst_0399.pmap
jwst_0016.pmap
jwst_0034.pmap
jwst_0125.pmap
jwst_0365.pmap
jwst_0591.pmap
jwst_0365.pmap
jwst_0357.pmap
jwst_0541.pmap
jwst_miri_flat_0002.rmap
jwst_miri_0011.imap
jwst_miri_dark_0008.rmap
jwst_miri.imap)

jwstrefs=(jwst_niriss_flat_0000.fits jwst_miri_flat_0006.fits)

export CRDS_SERVER_URL=https://jwst-crds.stsci.edu
export CRDS_CONTEXT=jwst-operational
for ctx in ${jwstcontexts[@]}
do
    echo "Syncing mappings under ${ctx}"
    python -m crds.sync --contexts $ctx --stats --log-time --check-sha1sum --repair-files --organize=flat
done
echo "Syncing JWST current operational context"
python -m crds.sync --contexts jwst-operational --stats --log-time --check-sha1sum --repair-files --organize=flat
echo "Syncing JWST select reference files"
python -m crds.sync --files ${jwstrefs[@]} --stats --log-time

