#!/bin/bash
source ${HOME}/scripts/hst-crds-config
source ${HOME}/scripts/image-config

# check for mounted test cache, otherwise move cache to mount directory 
${HOME}/scripts/config-cache-mount $CACHE_SRC

if [[ -z $CRDS_SERVER_URL ]]; then
    echo "Setting server url"
    export CRDS_SERVER_URL=https://hst-crds.stsci.edu
    echo "CRDS SERVER URL set to: ${CRDS_SERVER_URL}"
fi


# check crds installation
resp=`crds list --status`
status=`echo $resp | cut -f1 -d'='`

cd ${HOME}/crds

if [[ -z $status ]]; then
    echo "Installing CRDS client code"
    # install mounted crds source code
    ./install && pip install -e .[submission,test,docs,synphot] 
    pip install --upgrade .["submission","test"]
fi

# set CRDS CONTEXT
if [[ -z $CRDS_CONTEXT ]]; then
    export CRDS_CONTEXT=hst-latest
    # summary=`crds list --status` 
    context_num=`echo $resp | cut -f8 -d'=' | cut -f2 -d'_' | cut -f1 -d'.'`
    latest_context="hst_${context_num}.pmap"
    export CRDS_CONTEXT=$latest_context
fi

echo "CRDS_SERVER_URL: ${CRDS_SERVER_URL}"
echo "CRDS_CONTEXT: ${CRDS_CONTEXT}"


./runtests
cd $HOME
