#!/bin/bash
###########################################
# USER SETTINGS - configure these as needed
###########################################

##### image tag #####
# select or enter an image tag ("latest", "slim", or custom)

## "latest" : built-in test data  (4.26 GB)
export IMAGE_TAG="latest"

## "slim" : mount your existing test data directories (3.34 GB)
# export IMAGE_TAG="slim"

## enter a custom tag (e.g. 'dev') if building your own image (or use "latest")
# export IMAGE_TAG=

##### test suite data #####
# Put existing crds test suite cache data inside the "cache_volumes" folder if you
# want these mounted into the container at runtime
export CACHE_SRC="cache_volumes"
# If you don't have the crds test cache data or want to start fresh, set these = 1
# DOWNLOAD=1 : clones github.com/spacetelescope/crds-test-cache 
export DOWNLOAD=1
# SYNC=1 : runs crds.sync for crds-default-test-cache 
export SYNC=1

##### API Testing config (optional - not used in test suite) #####
# optionally set MAST token as env var (for API testing/jupyter)
export MAST_API_TOKEN=""
export CRDS_CONTEXT=""
export CRDS_SERVER_URL=""

##### mounting CRDS client code #####
export GH_USER="alphasentaurii"
export CRDS_BRANCH="master"
## pathfinder script tries to find abs local paths of this repo and crds client
## for shared folder mounting into the container
source scripts/pathfinder
## *** If CRDS is in a different location than this repo, you can just
## *** comment out `source scripts/pathfinder` and set the paths explicitly

## abs local path to this repo:
# export SHOME=/top/path/to/this/code

## abs local path to CRDS client source code:
# export CRDS_ROOT=/abs/path/to/my/crds/client/code
